Add feature repository and types
aivara-se/provar.se pull request #10
Opened 2023-10-18 17:32 UTC by N-i-z

2023-10-18 19:28 UTC, thani-sh requested changes

2023-10-18 19:28 UTC, thani-sh commented on apps/webapp/src/lib/server/features/features.types.ts
> +export interface Features {
Use singular form unless its an array

```suggestion
export interface Feature {
```

2023-10-18 19:28 UTC, thani-sh commented on apps/webapp/src/lib/server/features/features.repository.ts
> +export async function findByName(name: string): Promise<Features | null> {
We won't need this function. I'll explain later.

2023-10-18 19:28 UTC, thani-sh commented on apps/webapp/src/lib/server/features/features.repository.ts
> +    name: string;
Can you add a `key` field here and a `findByKey` function.

We can also add an `organizationId` field here so we can find out to which organization this feature belongs to. It'll also help to have a function to get all features that belong to an organization ( `findByOrganization` perhaps ).

You can check the `findByMember` function on organization repository file for an example where we query and fetch multiple documents.

2023-10-19 05:17 UTC, N-i-z commented on apps/webapp/src/lib/server/features/features.types.ts
> +export interface Features {
oki

2023-10-19 05:20 UTC, N-i-z commented on apps/webapp/src/lib/server/features/features.repository.ts
> +export async function findByName(name: string): Promise<Features | null> {
oki
as i said i just copy pasted the existing code and tweaked it a bit

2023-10-19 07:44 UTC, thani-sh requested changes

2023-10-19 07:44 UTC, thani-sh commented on apps/webapp/src/lib/server/features/feature.repository.ts
> +const COLLECTION_NAME = 'feature';
Use plural form

```suggestion
const COLLECTION_NAME = 'features';
```

2023-10-19 07:44 UTC, thani-sh commented on apps/webapp/src/lib/server/features/feature.repository.ts
> +    organization: string[];
Features (also projects and feedback) can only belong to one organization. Also it's more clear if we say that it's an id.

```suggestion
    organizationId: string;
```

2023-10-19 07:44 UTC, thani-sh commented on apps/webapp/src/lib/server/features/feature.repository.ts
> +export async function findByOrganisation(OrganizationId: string): Promise<Feature[]> {
Use lower camelCase for variable names.

```suggestion
export async function findByOrganisation(organizationId: string): Promise<Feature[]> {
```

2023-10-19 14:50 UTC, thani-sh requested changes

2023-10-19 14:50 UTC, thani-sh commented on apps/webapp/src/lib/server/features/feature.repository.ts
> +    organizationId: string;
Shall we change to ObjectId? Will be useful for some database queries

2023-10-19 14:50 UTC, thani-sh commented on apps/webapp/src/lib/server/features/feature.repository.ts
> +    const doc = await coll.findOne({ key: new String(key) });
No need to do `new String` here because it's already a string.

2023-10-19 16:02 UTC, N-i-z commented on apps/webapp/src/lib/server/features/feature.repository.ts
> +    organizationId: string;
umm change what to ObjectId?

2023-10-20 04:40 UTC, thani-sh commented on apps/webapp/src/lib/server/features/feature.repository.ts
> +export async function findByOrganisation(organizationId: ObjectId): Promise<Feature[]> {
We should a string `organizationId` as a parameter and convert it to an ObjectId inside the function. ( check `findById` for an example ).

2023-10-20 04:49 UTC, N-i-z commented on apps/webapp/src/lib/server/features/feature.repository.ts
> +export async function findByOrganisation(organizationId: ObjectId): Promise<Feature[]> {
this is confusing me too

2023-10-20 05:44 UTC, thani-sh approved these changes

2023-10-20 05:47 UTC, merged