Add feedback repository and types
aivara-se/provar.se pull request #8
Opened 2023-10-18 17:21 UTC by N-i-z

2023-10-18 19:28 UTC, thani-sh requested changes

2023-10-18 19:28 UTC, thani-sh commented on apps/webapp/src/lib/server/feedback/feedback.repository.ts
> +    _id: ObjectId;
Feedback belongs to an organization and also to a project. It'll be useful to add 2 more fields here `organizationId` and `projectId`. We can also add 2 helper functions `findByOrganization` and `findByProject`.

You can check the `findByMember` function on organization repository file for an example where we query and fetch multiple documents.

If you like a challenge, make `findByProject` function accept 2 parameters (projectId and organizationId) and use them both when querying for feedback from the database. I can explain later why we are using both fields instead of just the project id (remind me if I forgot).

2023-10-18 19:28 UTC, thani-sh commented on apps/webapp/src/lib/server/feedback/feedback.repository.ts
> +const COLLECTION_NAME = 'feedback';
Use plural form for collection names

```suggestion
const COLLECTION_NAME = 'feedbacks';
```

2023-10-18 19:28 UTC, thani-sh commented on apps/webapp/src/lib/server/feedback/feedback.repository.ts
> +    key: string;
Feedbacks don't have a key field, please remove this. It should be on features.

2023-10-19 06:49 UTC, N-i-z commented on apps/webapp/src/lib/server/feedback/feedback.repository.ts
> +    key: string;
yup got it

2023-10-19 06:50 UTC, N-i-z commented on apps/webapp/src/lib/server/feedback/feedback.repository.ts
> +const COLLECTION_NAME = 'feedback';
done

2023-10-19 10:57 UTC, N-i-z commented
i commited findByProject with just the project id for now
I'll try the two parameter one after I fix the other issues in the feature directory

2023-10-20 07:01 UTC, closed without merging